version: '3'

services:
  web:
    container_name: wot-authorization-server-web
    entrypoint: npm start -- --host 0.0.0.0 --live-reload-client "http://0.0.0.0:1337"
    volumes:
      - ./dashboard/src:/code/src
    links:
      - api
    ports:
      - "$WEB_PORT:4200"
    environment:
      - NODE_ENV=development

  api:
    container_name: wot-authorization-server-api
    entrypoint: npm start
    volumes:
      - ./api/src:/code/src
    links:
      - db
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      - NODE_ENV=development
      - PORT=$API_PORT
      - MONGODB_URI=mongodb://db/wot-authorization-server-api-dev
      - MASTER_KEY
      - JWT_SECRET
 
  db:
    container_name: wot-authorization-server-db
    image: mongo:latest
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
