version: '3'

services:

  web:
    container_name: wot-authorization-server-web-test
    entrypoint: yarn
    command: test
    links:
      - api
    ports:
      - "$WEB_PORT:4200"
    environment:
      - NODE_ENV=test

  api:
    container_name: wot-authorization-server-api-test
    entrypoint: yarn
    command: coverage
    links:
      - dbtest
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      - NODE_ENV=test
      - PORT=$API_PORT
      - MONGODB_URI=mongodb://dbtest/wot-authorization-server-api-test
      - MASTER_KEY
      - JWT_SECRET
 
  dbtest:
    container_name: wot-authorization-server-db-test
    image: mongo:latest
    volumes:
      - mongodatatest:/data/db

volumes:
  mongodatatest:
    driver: local
