version: '3'

services:

  web:
    env_file:
      - .test.env
    container_name: wot-authorization-server-web-test
    entrypoint: yarn
    command: test
    links:
      - api
    ports:
      - "$WEB_PORT:4200"
    environment:
      - NODE_ENV=test

  api:
    env_file:
      - .test.env
    container_name: wot-authorization-server-api
    entrypoint: yarn
    command: test
    links:
      - db
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      - NODE_ENV=test
      - PORT=$API_PORT
      - MONGODB_URI=mongodb://dbtest/wot-authorization-server-api-test
      - MASTER_KEY
      - JWT_SECRET
 
  dbtest:
    env_file:
      - .test.env
    container_name: wot-authorization-server-db
    image: mongo:latest
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
