version: '3'

services:

  proxy:
    build: ./proxy/
    container_name: wot-authorization-server-proxy
    ports:
      - "2015:2015"

  web:
    container_name: wot-authorization-server-web
    entrypoint: yarn
    command: start -- --host "0.0.0.0" --live-reload false --live-reload-client "http://localhost:2015"
    volumes:
      - ./dashboard/src:/code/src
    links:
      - api
    ports:
      - "$WEB_PORT:4200"
    environment:
      - NODE_ENV=development

  api:
    container_name: wot-authorization-server-api
    entrypoint: yarn
    command: start
    volumes:
      - ./api/src:/code/src
    links:
      - db
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      - NODE_ENV=development
      - PORT=$API_PORT
      - MONGODB_URI=mongodb://db/wot-authorization-server-api-dev
      - MASTER_ACCOUNT
      - MASTER_PASSWORD
      - MASTER_KEY
      - JWT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
 
  db:
    container_name: wot-authorization-server-db
    image: mongo:latest
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
